### ISSUE TITLE
Is apache environment still supported?

### ISSUE THREAD

**Issue by mazhe** [NASA-AMMOS/MMGIS#1]
Hi,

I have taken interest in MMGIS since the presentation at planetary data workshop in June and have played a bit with 1.0 release.

I've been using it in a apache configuration setting (well, actually nginx), but after upgrading to 1.1, I cannot get this configuration to work anymore and I notice "calls.api is only for node" despite having set SERVER=apache in the environment. I've noticed the SERVER setting is not documented anymore in the Readme (but still visible in the wiki), does this mean it is now deprecated to run MMGIS outside a node setup?

Thanks a lot for this tool and releasing it to the public!

-- Matthieu Volat

**Comment by tariqksoliman** [comment]
Hi and sorry. Yes, the apache side of things is getting deprecated. It's not too far off of being fully functional as it sits currently but we're set on using only node from now on and would rather not develop for two environments.

You're welcome and I'm glad you like it!
