### ISSUE TITLE
Small fix to apply to Dockerfile for Package updates

### ISSUE THREAD

**Issue by chris-david-taylor** [NASA-AMMOS/MMGIS#103]
In the Dockerfile on line 4,

apt-get update

Should read:

apt-get -y update

Otherwise the package lists will not be rebuilt and the container build can occasionally fail with the following output:

TST [docker@dt-mmgis-01][mmgis]$ docker-compose up -d
Building mmgis
Step 1/11 : FROM node:12
 ---> 7e90b11a78a2
Step 2/11 : RUN apt-get update
 ---> Using cache
 ---> 6c6c2e8b7d5e
Step 3/11 : RUN apt-get install -y gdal-bin libgdal-dev python3-pip python3-gdal
 ---> Running in e3700551437a
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package gdal-bin
E: Unable to locate package libgdal-dev
E: Unable to locate package python3-pip
E: Unable to locate package python3-gdal

**Comment by tariqksoliman** [comment]
Thank you and done! fb3e13b8ec8bb3e32726b5375d32928d0e817367
