### ISSUE TITLE
Globe Fill Color Default to Black on Opacity Change

### ISSUE THREAD

**Issue by tariqksoliman** [NASA-AMMOS/MMGIS#164]
To reproduce: make a polygon vector layer with a transparent fill, slide its opacity and compare the 2D and 3D views with expectation.

Also Fill Colors of "rgba(0,0,0,0)" should never be needed.

**Comment by wiserdivisor** [comment]
Can I still work on this bug and contribute?

**Comment by tariqksoliman** [comment]
Closing because this is indeed outdated -- this no longer seems to be an issue on later branches.
@wiserdivisor #270 or #144 (if you're on a Mac) would be good starting issues.
