### ISSUE TITLE
Administrator account cannot be created

### ISSUE THREAD

**Issue by ashankhdhar-HU** [NASA-AMMOS/MMGIS#18]
Hey everyone, 

I am trying to setup MMGIS so I can attempt to test its application on the Moon. I followed the setup instructions but http://localhost:8888/configure landed on the login page. I rebuilt my environment and restarted the server and still ended up on the login page preventing me from creating a new account. 

Any suggestions on how to get around that?

**Comment by tariqksoliman** [comment]
Hi ashankhdhar-HU,
Could you post the stdout after running `npm run start:prod` (or `npm start` and scroll up). It sound's like Postgres isn't setup properly.

**Comment by ashankhdhar-HU** [comment]
Hey tariqksoliman,

I expected that there was something with Postgres as I was reading thee setup instructions but a teammate ran into the same issue as me.

Running the `npm run start:prod`

> npm run start:prod
> npm ERR! missing script: start:prod
> npm ERR! 
> npm ERR! Did you mean this?
> npm ERR!     start
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/ashankhdhar/.npm/_logs/2021-01-22T02_33_35_479Z-debug.log
> 

The log `/Users/ashankhdhar/.npm/_logs/2021-01-22T02_33_35_479Z-debug.log`

> 1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start:prod' ]
> 2 info using npm@6.14.10
> 3 info using node@v14.15.4
> 4 verbose stack Error: missing script: start:prod
> 4 verbose stack
> 4 verbose stack Did you mean this?
> 4 verbose stack     start
> 4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:155:19)
> 4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:63:5
> 4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:116:5
> 4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:5
> 4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:391:45)
> 4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:434:3)
> 4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:161:5)
> 4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:281:12
> 4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:123:16
> 4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
> 5 verbose cwd /Users/ashankhdhar/Documents/MMGIS-master
> 6 verbose Darwin 19.6.0
> 7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start:prod"
> 8 verbose node v14.15.4
> 9 verbose npm  v6.14.10
> 10 error missing script: start:prod
> 10 error
> 10 error Did you mean this?
> 10 error     start
> 11 verbose exit [ 1, true ]

**Comment by tariqksoliman** [comment]
`npm run start:prod` should be run in the project root (and after `npm start` and `npm run build`).

**Comment by ashankhdhar-HU** [comment]
Hey tariqksoliman, 

We continue to hit the same issue even when we run `npm run start:prod` from the root directory of the MMGIS project. We cleared our environment, pulled the repo down again and set everything up but it ended with the same error. Also got a a very similar error when we ran `npm run start:build`

> [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start:build
> ' ]
> 2 info using npm@6.14.10
> 3 info using node@v14.15.4
> 4 verbose stack Error: missing script: start:build
> 4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:15
> 5:19)
> 4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:63:5
> 4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:116:5
> 4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:5
> 4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:391:45)
> 4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:434:3)
> 4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:161:5)
> 4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:382:12
> 4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:123:16
> 4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

**Comment by tariqksoliman** [comment]
`start:prod` is just an alias command in the [package.json](https://github.com/NASA-AMMOS/MMGIS/blob/2.0.0/package.json#L40). It `cross-env NODE_ENV=production` set the `NODE_ENV` environment variable to `production` and should work for multiple environments (`cross-env`) and then it runs `run/server.js` with node. Try doing these two things manually.

`start:build` isn't a command.

**Comment by tariqksoliman** [comment]
Actually this doesn't address you first issue. If you could post the results of "or `npm start` and scroll up", that would help.

**Comment by ashankhdhar-HU** [comment]
Oh I see. Yes based on the output of `npm start` it looks like I am on v1.3.5. Below is the output you requested:

> mmgis@1.3.5 start /Users/ashankhdhar/Documents/MMGIS-master
> node server.js
> 
> {"level":"info","ts":1611524878964,"caller":"server","msg":"MMGIS successfully started! It's listening on port: 8888","domain":"HOST","hostname":"C02Y61JDJGH5","sessionID":"HOST","internalSessionID":"HOST","user":"HOST"}
> {"level":"info","ts":1611524878966,"caller":"testEnv","msg":{"SERVER":"node","PORT":"8888","AUTH":"none","NODE_ENV":"development","SECRET":"_redacted_","VERBOSE_LOGGING":"false","ALLOW_EMBED":"false","DISABLE_LINK_SHORTENER":"false","DB_HOST":"localhost","DB_PORT":"8888","DB_NAME":"mmgis","DB_USER":"postgres","DB_PASS":"_redacted_","HIDE_CONFIG":"false","CONFIGCONFIG_PATH":"","FORCE_CONFIG_PATH":"","CSSO_GROUPS":"[\"A\", \"B\"]","CSSO_LEAD_GROUP":"A","LEADS":"[\"user1\"]"},"domain":"HOST","hostname":"C02Y61JDJGH5","sessionID":"HOST","internalSessionID":"HOST","user":"HOST"}
> {"level":"info","ts":1611524878966,"caller":"testEnv","msg":"The following env variable is empty: CONFIGCONFIG_PATH","domain":"HOST","hostname":"C02Y61JDJGH5","sessionID":"HOST","internalSessionID":"HOST","user":"HOST"}
> {"level":"info","ts":1611524878966,"caller":"testEnv","msg":"The following env variable is empty: FORCE_CONFIG_PATH","domain":"HOST","hostname":"C02Y61JDJGH5","sessionID":"HOST","internalSessionID":"HOST","user":"HOST"}

I can clear my environment and attempt all this again using v2.0 as well

**Comment by tariqksoliman** [comment]
Yeah, `PORT` and `DB_PORT` shouldn't be the same port. If you never reconfigured the Postgres port, it should still be `5432`.

**Comment by ashankhdhar-HU** [comment]
Hey tariqksoliman, 

Pulling the v2.0 and making the changes you suggested did the trick. I will close the issue! Thanks for the help
