### ISSUE TITLE
There does not seem to be any mission data such as the map or any images

### ISSUE THREAD

**Issue by grimdeathr** [NASA-AMMOS/MMGIS#184]
This is the error i see :

`Failed to load resource: the server responded with a status of 404 (Not Found)
:8888/Missions/add1/Layers/Waypoints/waypoints.json:1          Failed to load resource: the server responded with a status of 404 (Not Found)
LayerCapturer.js:194 ERROR! error in Missions/add1/Layers/Waypoints/waypoints.json /// Not Found
(anonymous) @ LayerCapturer.js:194
:8888/Missions/add1/Layers/ChemCam/chemcam.json:1          Failed to load resource: the server responded with a status of 404 (Not Found)
LayerCapturer.js:194 ERROR! error in Missions/add1/Layers/ChemCam/chemcam.json /// Not Found
(anonymous) @ LayerCapturer.js:194
Layers_.js:1240 Warning: Tried to get Tool: layers's config variables and failed.
getToolVars @ Layers_.js:1240
Layers_.js:1240 Warning: Tried to get Tool: isochrone's config variables and failed.
getToolVars @ Layers_.js:1240
Layers_.js:1240 Warning: Tried to get Tool: viewshed's config variables and failed.
getToolVars @ Layers_.js:1240
ViewshedTool.js:79 ViewshedTool: variables object does not contain key "data"!
initialize @ ViewshedTool.js:79
Layers_.js:1240 Warning: Tried to get Tool: draw's config variables and failed.
getToolVars @ Layers_.js:1240
31917.png:1          Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by grimdeathr** [comment]
<img width="1894" alt="image" src="https://user-images.githubusercontent.com/96903806/168668312-5be0bc77-26b5-431e-b1df-e3a01bb08ac2.png">

**Comment by tariqksoliman** [comment]
Hi! It looks like you're trying to view the Test mission data. It should automatically setup that data is you name the new mission "Test" rather than "add1". Alternatively you can copy the contents of https://github.com/NASA-AMMOS/MMGIS/tree/master/prepare/base/Missions/Test into `Missions/add1`
