### ISSUE TITLE
API - Layers should only query source on visible

### ISSUE THREAD

**Issue by davetsay** [NASA-AMMOS/MMGIS#190]
Currently all the layers (or maybe just time based ones) are querying whether they are visible or not. This increases initial load time significantly and reduces the user experience.

**Comment by davetsay** [comment]
What I filed originally might not be correct. I believe the real bug is that layers that have been hidden after being visible continue to reload and re-query behind the scenes.

I'll do some more testing to make sure what is happening.

**Comment by khalidadil** [comment]
For some specifics, I'm seeing our rover pose layer (a time enabled vector layer loaded from a url) issue network requests when the time bounds are set in MMGIS despite the layer being disabled/not visible.

**Comment by tariqksoliman** [comment]
Could you try the ts-190 branch and see if it fixes this issue. I mainly just made it so that time layers can only reload if they're on.

**Comment by khalidadil** [comment]
@tariqksoliman I believe I'm still seeing this issue. In the video you can see that I have all the layers turned off, but when the time conductor of OpenMCT sets new time bounds for MMGIS, there are still network requests firing.

https://user-images.githubusercontent.com/2343076/173117605-4a96a214-d2d2-4d61-9a63-31c5ceda0bfc.mov

**Comment by davetsay** [comment]
@tariqksoliman tested and verified fixed
