### ISSUE TITLE
Multiple rover image requests when using mmgisAPI

### ISSUE THREAD

**Issue by tariqksoliman** [NASA-AMMOS/MMGIS#200]
Raw Variables' `markerAttachment.image.url` gets called repeatedly when updating its vector layer through the mmgisAPI.

**Comment by khalidadil** [comment]
Note that this happens while using the built in rover images (see attachment):
![Screen Shot 2023-05-15 at 2 58 17 PM](https://github.com/NASA-AMMOS/MMGIS/assets/2343076/0dbe040c-351f-4ddb-a4df-be84fcedc9cd)

The marker settings we're using are:
"path": "public/images/rovers/CuriosityTopDownOrthoSmall.png"

**Comment by khalidadil** [comment]
I posted an example of this happening earlier today...but I suppose if you want to be able to see cached images working properly, you shouldn't have the "Disable cache" option checked in devtools! 😵‍💫 

Note that this was using an image via a docker volume aliased to public/images/rovers to mimic where the internal rover images are located.
