### ISSUE TITLE
Nested layer expand/collapse state incorrect on parent expansion

### ISSUE THREAD

**Issue by davetsay** [NASA-AMMOS/MMGIS#270]
Steps to reproduce
1. expand a header layer than contains nested header layers
2. change the state of the nested layer (expand or collapse it)
3. collapse the original parent layer
4. expand the original parent layer

The state of the nested layer indicator is not correct based on its  actual state

https://user-images.githubusercontent.com/3614296/200950700-c67df852-48d5-4036-9f42-082b84556acc.mov

**Comment by wiserdivisor** [comment]
Please assign me to this issue 😲

**Comment by tariqksoliman** [comment]
Hi and this task doesn't need any special data to test.

Layers would need to be configured in the /configure page Layers Tab. A new header layer could be added with the "Add Layer" button at the bottom and then more layers could be added and then drag-and-dropped under that header layer. The actual datasets layers use here are irrelevant.

![326744568339329](https://github.com/NASA-AMMOS/MMGIS/assets/25355244/de076ec7-7a52-4f55-bbb1-5214a1962391)

And some documentation: https://nasa-ammos.github.io/MMGIS/configure/tabs/layers
