### ISSUE TITLE
[FEATURE] Plugin API for Instrument Data

### ISSUE THREAD

**Issue by cstatz** [NASA-AMMOS/MMGIS#30]
**Is your feature request related to a problem? Please describe.**
It would be useful to be able to natively overlay/display instrument data or simulations in MMGIS and specific instrument related tools.
Currently, only the display of Chemistry taken by ChemCam is possible.

**Describe a possible solution.**
Provide a plugin api, that allows the development and integration of instrument specific tools into the MMGIS workflow.
This api would provide access to the map and 3d views.

**Describe alternatives you've considered**
Convert the instrument data into Tiles/Data/Vector Tiles. Convert the instrument results to paths/lines/points/polygons or images. Allow manual steps in the workflow (i.e., export and import of .geojson).

**Comment by cstatz** [comment]
Thanks for the hint! I'll have a look at this and check if I can implement the feature based on this.

**Comment by fcalef** [comment]
I'm going to close the ticket, but feel free to reopen it or make a new issue as necessary.
