### ISSUE TITLE
Expose as much as possible to the mmgisAPI

### ISSUE THREAD

**Issue by tariqksoliman** [NASA-AMMOS/MMGIS#313]
Such as all the utility formulas and everything (reasonable) in Layers. Document as well.

**Comment by The-Outrider** [comment]
validateTokenKey would also be nice.

**Comment by tariqksoliman** [comment]
@The-Outrider Could you explain that more or provide a use case? Are the tokens here the API Tokens used to interact with the Configure API.

(
For some definitions:
- mmgisAPI = JavaScript API = applications wrapping MMGIS would use this to interface with the client-instance of MMGIS = called with JavaScript
- Configure API = backend REST API that requires auth = modifies the MMGIS configuration for the whole mission for all users = called with curl/fetch/whatnot  

)

**Comment by The-Outrider** [comment]
Hey Tariq,
![Screen Shot 2023-02-09 at 09 45 51](https://user-images.githubusercontent.com/6240904/217863197-9e9c721a-aa7f-4a7b-81fe-3eceea5468af.png)

Yah its for the Configure API, the basic idea is to have a check if the API token is set and is still valid. This would displayed on the frontend.  (See screenshot)

**Comment by tariqksoliman** [comment]
Okay, I see what you mean now.

**Comment by tariqksoliman** [comment]
@The-Outrider Hi! See what I've added here: https://github.com/NASA-AMMOS/MMGIS/pull/330 and of course I can always add more on request.
