### ISSUE TITLE
Feature Request: GetMissions

### ISSUE THREAD

**Issue by The-Outrider** [NASA-AMMOS/MMGIS#335]
I'd like to see GetMissions also return its config object and latest version.

Instead of returning an array `["Mission1", "Mission2"]`

do

`[{
  name: "Mission1"
  config: {}
  version: 32
}]`

At the moment I have to make 3 API calls to get all this information.

**Comment by tariqksoliman** [comment]
Hi and done! Please see #345

Simply adding `?full=true` to the `/api/configure/missions` call will return `{ missions: [{ name: "Mission1" config: {} version: 32 }] }`
