### ISSUE TITLE
Map Zoom Control toggle not active

### ISSUE THREAD

**Issue by pgbrodrick** [NASA-AMMOS/MMGIS#339]
Hey All, 

I'm running off of: 228bede34bb12a863906911c8285848bf2e03119

I'm seeing that the Map Zoom Control toggle no longer seems to work (it's appears off regardless of whether toggled on or off).

**Comment by tariqksoliman** [comment]
@pgbrodrick Any chance you also have `Miscellaneous` unchecked? Toggling `Map Zoom Control` works but an unchecked `Miscellaneous` overrides it. If so, I can decouple the two and make them independent as the UI here suggests.

**Comment by pgbrodrick** [comment]
Aha!  Yes, this was it.  Happy to just check that for my case, but it might be worth decoupling for others.  Thanks!

**Comment by tariqksoliman** [comment]
Closing for now and until it's a full ask.
