### ISSUE TITLE
[Bug]: Copy Link button creates not unshareable URL with spaces 

### ISSUE THREAD

**Issue by sschmaus** [NASA-AMMOS/MMGIS#346]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

When creating a shareable link with the `Copy Link` button, the copied URL contains spaces ` `. These spaces appear for layers that have spaces in their name. 
Pasting this URL on any social media platform will not create a clickable link, because a Link is expected not to contain spaces. Instead the clickable Link ends after the first space character and the rest remains as normal text. 

```
https://mars.nasa.gov/maps/location/?mission=M20&site=NOW&mapLon=77.40218639461092&mapLat=18.469829969516443&mapZoom=15&globeLon=77.42958068847659&globeLat=18.463327291058505&globeZoom=12&globeCamera=0,-4882.8125,0,0,1,0&panePercents=0,100,0&on=Rover Position$1.00,Rover Waypoints$1.00,Rover Drive Path$1.00,Sampling Locations$1.00,Surface View$1.00,Helicopter Position$1.00,Helicopter Waypoints$1.00,Helicopter Flight Path$1.00,Flight Test Zone$1.00,Labels$1.00,Color Basemap$1.00,Grayscale Basemap$1.00,Northeast Syrtis Base Map$1.00
```

Example Twitter: 
![image](https://user-images.githubusercontent.com/32999741/221150462-9f848757-7226-4d38-b872-2168212533e0.png)

### What did you expect?

The spaces should be converted to their HTML `%20` encoding. This happens anyways when the link will be pasted directly in a new browser window:

```
https://mars.nasa.gov/maps/location/?mission=M20&site=NOW&mapLon=77.40218639461092&mapLat=18.469829969516443&mapZoom=15&globeLon=77.42958068847659&globeLat=18.463327291058505&globeZoom=12&globeCamera=0,-4882.8125,0,0,1,0&panePercents=0,100,0&on=Rover%20Position$1.00,Rover%20Waypoints$1.00,Rover%20Drive%20Path$1.00,Sampling%20Locations$1.00,Surface%20View$1.00,Helicopter%20Position$1.00,Helicopter%20Waypoints$1.00,Helicopter%20Flight%20Path$1.00,Flight%20Test%20Zone$1.00,Labels$1.00,Color%20Basemap$1.00,Grayscale%20Basemap$1.00,Northeast%20Syrtis%20Base%20Map$1.00
```

### Reproducible steps

Use the `Copy Link`button on the mars 2020 mission tracker page: https://mars.nasa.gov/mars2020/mission/where-is-the-rover/

**Comment by tariqksoliman** [comment]
Thank you! It may take a while for the Where is the Rover instance of MMGIS to get updated but I will pass this issue along to them.

_Other notes for my own completeness:_
- This is not an issue in later versions of MMGIS because we use spaceless UUIDs instead of freeform strings to identify layers.
- This is only an issue when the link shortener is disabled. Something like `http://localhost:8889/?s=1cvun` is always a proper url and the expansion of it always encodes properly too.
