### ISSUE TITLE
adding layers to map

### ISSUE THREAD

**Issue by miladad8** [NASA-AMMOS/MMGIS#35]
hi.  feature layers in viewer panel are greyed out. do i have to add layers manually to database or download them from somewhere? sorry i'm very naive and new with this. i would really appreciate if someone walk me through this process.
![Screenshot (1152)](https://user-images.githubusercontent.com/81193047/112059507-8bf00a00-8b79-11eb-8004-90607dcaf047.png)

**Comment by tariqksoliman** [comment]
Hi miladad8,
So yes, the redden-out vector layers indicate that the layer couldn't be loaded -- either it couldn't find the data or there's an error in the data.

It looks like you're trying to get the "Test" mission setup and have already set it up as a "new mission" from /configure. The data for the Test mission is included in the repo. You'll need to copy over the `/prepare/base/Missions/Test` directory to `/Missions/Test` and possible set read permissions on the directory and/or restart MMGIS.

Alternatively you can try configuring layers yourself with your own data (the Test data is very minimal and is meant only as a brief example) via the /configure page. There are docs at `https://<your_domain>/docs` (or immediately at https://github.com/NASA-AMMOS/MMGIS/wiki/Documentation) that should offer some assistance.

Hope this helps!

**Comment by miladad8** [comment]
thank you very much sir! as you said  i set up a new mission and that is why i got confused and couldn't follow the tutorial and docs. again thank you very very much for your kindness and help.
