### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by tariqksoliman** [NASA-AMMOS/MMGIS#365]

**Comment by whatnick** [comment]
Dev and Production dependencies are mixed in and will probably lead to building of larger bundles and slower load times than necessary. On examining `package.json` , there are dev dependencies such as jest, webpack-dev server and others.
https://github.com/NASA-AMMOS/MMGIS/blob/dc4d7ff352c5e1ebc14b4c902ca4ba69dc11f87d/package.json#L100
Happy to assist in building cleaner dependency structure and enabling automation to allow PR's of stale ones using dependabot or similar.

**Comment by tariqksoliman** [comment]
Hi @whatnick and you're completely correct. Any help organizing the dependencies would be much appreciated! The main working branch is `development` too.

**Comment by whatnick** [comment]
Sorry never found the time to assist you with this. Glad you managed to fit
it in.
