### ISSUE TITLE
[Bug]: calls to `updateVectorLayer` and `appendLineString` cause selected feature to be deselected when using info tool

### ISSUE THREAD

**Issue by davetsay** [NASA-AMMOS/MMGIS#372]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

API Calls `updateVectorLayer` and `appendLineString` will de-select the selected feature. I would assume other api calls that similarly modify vector layers would cause the same behavior.

### What did you expect?

The selected feature remains selected

### Reproducible steps

```bash
1. Use the info tool and select a feature
2. Use the javascript API to update a layer that is different than the layer of the selected feature
3. observe that the selected feature is deselected, the metadata disappears
```

### Environment

```bash
- Version of this software v2.8.0
```

**Comment by khalidadil** [comment]
Calling these api endpoints also closes the properties pane while editing a drawn polygon’s details.
