### ISSUE TITLE
[Bug]: Issue with rover image marker alignment to feature alignment

### ISSUE THREAD

**Issue by khalidadil** [NASA-AMMOS/MMGIS#382]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

When playing back simulated rover data, we're occasionally noticing that the rover image marker doesn't align with the feature marker (blue dot with arrow). The image marker is located at the correct location, but is pointing in the wrong direction. We need more investigation to determine exactly when this happens. Here's an example:

![Screen Shot 2023-05-15 at 1 47 01 PM](https://github.com/NASA-AMMOS/MMGIS/assets/2343076/4af4f802-5c2b-4ba9-92c1-1bd1f61561bf)

### What did you expect?

I expected the rover image marker direction to match the feature arrow direction.

**Comment by wiserdivisor** [comment]
Can I still work on this bug and contribute?

**Comment by khalidadil** [comment]
We were talking about this earlier today. We haven't really tested this case recently, but I haven't seen it lately with the test data we have in the system.
