### ISSUE TITLE
setTime API does not seem to set start time

### ISSUE THREAD

**Issue by tamarmot** [NASA-AMMOS/MMGIS#519]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

When I used the setTime api to set the times, and then used the getStartTime and getEndTime api, the getStartTime used the time from the URL, and was not updated.

### What did you expect?

both start time and end time to be updated.

### Reproducible steps

```bash
1.window.mmgisAPI.setTime('2024-11-13T08:00Z', '2024-11-13T11:00Z', false)
2.window.mmgisAPI.getStartTime()
3. result should be '2024-11-13T08:00Z'
```

**Comment by tariqksoliman** [comment]
@tamarmot See PR #520
