### ISSUE TITLE
[Bug]: Polygons in a geojson not showing   

### ISSUE THREAD

**Issue by sparkvilla** [NASA-AMMOS/MMGIS#594]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

I am trying to show two polygons with coords defined in a geojson file but the polygons are not showing up in the app

### What did you expect?

I expect to see those polygons showing up in a precise location on the map

### Reproducible steps

```bash
I uploaded my geojson file using the gui through "manage geodataset" and I then refer to it in the json configuration file. Here is the relevant part: 
 
     "layers": [
        {
          "name": "Flight Boxes",
          ...
          "sublayers": [
            {
              ...
              "type": "vector",
              "url": "geodatasets:{my_geojson_file_name}",
         
....

This does not seem to work. 
I have also tried to put the geojson file directly in the `Missions` folder. This folder is in my home folder with the following structure:

    /home/../Missions/Experiment_Name/Layers/my_geojson_file_name.geojson 

Then I would change the json configuration file to this:

     "layers": [
        {
          "name": "Flight Boxes",
          ...
          "sublayers": [
            {
              ...
              "type": "vector",
              "url": "/home/../Missions/Experiment_Name/Layers/my_geojson_file_name.geojson ",
         
....

but still, I can't see the data on the map. Could you help me to debug this?
Thank you in advance
```

### Environment

```bash
- I am running the app through the docker container 
- Ubuntu server 22.04.4
- Not sure about the software version, where can I find this info?
```

**Comment by tariqksoliman** [comment]
Hmm,

Regarding the geodataset:
- did you see any errors in the network tab of the developer's tool when uploading the geojson file?
- Any errors in the main application either?
- Does something `curl -X GET http://localhost:8889/api/geodatasets/get/my_geodataset?type=geojson` return anything?
- For the url, did you, say, upload a file called `my_geojson.json`, name it as a geodataset called "my_geodataset" and then reference it in a vector layer's url as `geodatasets:my_geodataset`

For the file directly in the `Missions` folder:
- Try setting it to `Layers/my_geojson_file_name.geojson`. All relative paths are already relative to `Missions/{mission_name}`.

One last thought is that maybe your geometries are in latlng order instead of lnglat order and are showing up somewhere unexpected because of that.

Let me know how it goes.

**Comment by sparkvilla** [comment]
Thank you for your replay @tariqksoliman . Try to answer your questions

- There are no errors when uploading the geojson file 
- In the main application, looking at the web-ui there are no errors. Anyway, see next point ..
- I think this is the problem. When executing the `curl` command you posted I get:
  
       {"status":"failure","message":"Failed to query Geodataset."}
   at the client side

and this 


    db-1     | 2024-10-30 08:16:08.142 UTC [59] ERROR:  relation "gnan_geodatasets" does not exist at character 48
    db-1     | 2024-10-30 08:16:08.142 UTC [59] STATEMENT:  SELECT properties, ST_AsGeoJSON(geom), id FROM gNaN_geodatasets;
    mmgis-1  | {"level":"error","ts":1730276168143,"caller":"/api/geodatasets/get/aviris_ng_001? type=geojson","msg":"Geodataset query SQL      
    error.","domain":"localhost:8888","hostname":"b33a98f874a0","sessionID":"HOST","internalSessionID":"XNG1Od7474Y    

    KhhK51QXObnnFAllR5KXu","user":"guest","req":{"query":{"type":"geojson","layer":"aviris_ng_001"}},"err":   {"name":"SequelizeDatabaseError","parent":   

    {"length":115,"name":"error","severity":"ERROR","code":"42P01","position":"48","file":"parse_relation.c","line":"1177","routine":"parserOpenTable","sql":"SELECT properties, ST_AsGeoJSON(geom), id FROM gNaN_geodatasets;"},"original":      {"length":115,"name":"error","severity":"ERROR","code":"42P01","position":"48","file":"parse_relation.c","line":"1177","routine":"parserOpenTable","sql":"SELECT properties, ST_AsGeoJSON(geom), id FROM gNaN_geodatasets;"},"sql":"SELECT properties, ST_AsGeoJSON(geom), id FROM gNaN_geodatasets;","parameters":{}}}


at the server side. 

- I tried with the relative path, i.e.  setting `Layers/my_geojson_file_name.geojson` but no success..

About the geometries, they are corrected because I use the exact same geojson file on my local machine at it works, i.e. the polygons are displayed. This is also what I am trying to do, i.e. compare the settings for the app running on my local machine (that works) and on the server (where it doesn't). 
     
Indeed on the server, when starting the docker container I get additional infos that are not present on my local machine, not sure if that can help:


    mmgis-1  | {"level":"info","ts":1730275894370,"caller":"testEnv","msg":    {"SERVER":"node","PORT":8888,"AUTH":"none","NODE_ENV":"production","SECRET":"_redacted_","VERBOSE_LOG

    GING":"false","ALLOW_EMBED":false,"DISABLE_LINK_SHORTENER":"false","DB_HOST":"mmgis-db-1","DB_PORT":"5432","DB_NAME":"db","DB_USER":"postgres","DB_PASS":"_redacted_","HIDE_CONFIG":"false"," 

    FORCE_CONFIG_PATH":"","CSSO_GROUPS":"[\"A\", \"B\"]","CSSO_LEAD_GROUP":"A","LEADS":"[\"user1\"]"},"domain":"HOST","hostname":"b33a98f874a0","sessionID":"HOST","internalSessionID":"HOST","user":"HOST"}

    mmgis-1  | {"level":"info","ts":1730275894373,"caller":"testEnv","msg":"The following env variable is empty: ALLOW_EMBED","domain":"HOST","hostname":"b33a98f874a0","sessionID":"HOST","internalSessionID":"HOST","user":"HOST"}

    mmgis-1  | {"level":"info","ts":1730275894377,"caller":"testEnv","msg":"The following env variable is empty: FORCE_CONFIG_PATH","domain":"HOST","hostname":"b33a98f874a0","sessionID":"HOST","internalSessionID":"HOST","user":"HOST"}

    mmgis-1  | {"level":"success","ts":1730275894380,"caller":"server","msg":"MMGIS successfully started! It's listening on port: 8888","domain":"HOST","hostname":"b33a98f874a0","sessionID":"HOST","internalSessionID":"HOST","user":"HOST"}

    mmgis-1  | Starting websocket...
mmgis-1  | 

    mmgis-1  | {"level":"info","ts":1730275894392,"caller":"websocket","msg":"Trying to init websocket...","domain":"HOST","hostname":"b33a98f874a0","sessionID":"HOST","internalSessionID":"HOST","user":"HOST"}

    mmgis-1  | {"level":"info","ts":1730275894392,"caller":"websocket","msg":"Server is valid so still trying to init websocket...","domain":"HOST","hostname":"b33a98f874a0","sessionID":"HOST","internalSessionID":"HOST","user":"HOST"}

    mmgis-1  | {"level":"info","ts":1730275894436,"caller":"connection","msg":"Database connection has successfully been established.","domain":"HOST","hostname":"b33a98f874a0","sessionID":"HOST","internalSessionID":"HOST","user":"HOST"}

    mmgis-1  | {"level":"success","ts":1730275894503,"caller":"server","msg":"All needed tables exist or have been successfully created!","domain":"HOST","hostname":"b33a98f874a0","sessionID":"HOST","internalSessionID":"HOST","user":"HOST"}

    mmgis-1  | {"level":"success","ts":1730275894504,"caller":"server","msg":"Called /webhooks/entries API","domain":"HOST","hostname":"b33a98f874a0","sessionID":"HOST","internalSessionID":"HOST","user":"HOST"}

    mmgis-1  | {"level":"success","ts":1730276020502,"caller":"/api/webhooks/entries","msg":"Called /webhooks/entries API","domain":"172.23.65.124:8888","hostname":"b33a98f874a0","sessionID":"HOST","internalSessionID":"EW8JcoV_EZEgeNqQ6YiIsHFLfcxo7yop","user":"rslAdmin"}

**Comment by tariqksoliman** [comment]
I did just push a small fix to `development` branch: https://github.com/NASA-AMMOS/MMGIS/commit/066447aeabeae8fadca5708939acbd86eaa0cdf8
That should fix the "NaN" in the `gNaN_geodatasets` table name but I don't think that'll fix anything functionally -- it might though.

Other than that to debug further, I would try running that command `SELECT properties, ST_AsGeoJSON(geom), id FROM gNaN_geodatasets;` directly on the postgres database and verify that a `gNaN_geodatasets` exists and that, in the `geodatasets` table, there's the relation between the geodataset name and its g* table's name. See the image:

geodatasets table example:
![4389673457](https://github.com/user-attachments/assets/0b865adf-4321-4de8-840f-744139e755fa)
Essentially you should see a row with a `name` "aviris_ng_001" with an `id` and pointing to an existing `table` that holds the geodataset data.

**Comment by sparkvilla** [comment]
So, here is what I did:
1. Entering the running `mmgis-db-1` container 
2. Connecting to the postgresql db 
3. Switching to the `db` database that contains the  `gNaN_geodatasets` table
 when listing all the tables in this db I get:

        db=# \dt;
                List of relations
        Schema |         Name         | Type  |  Owner   
        --------+----------------------+-------+----------
        public | configs              | table | postgres
        public | datasets             | table | postgres
        public | file_histories       | table | postgres
        public | file_histories_tests | table | postgres
        public | gNaN_geodatasets     | table | postgres
        public | geodatasets          | table | postgres
        public | long_term_tokens     | table | postgres
       public | published_stores     | table | postgres
       public | publisheds           | table | postgres
       public | publisheds_tests     | table | postgres
       public | session              | table | postgres
       public | spatial_ref_sys      | table | postgres
       public | url_shorteners       | table | postgres
       public | user_features        | table | postgres
       public | user_features_tests  | table | postgres
       public | user_files           | table | postgres
       public | user_files_tests     | table | postgres
       public | users                | table | postgres
       public | webhooks             | table | postgres

From here it looks like that the table `gNaN_geodatasets` does exist. However, when running, your command:

    db=# SELECT properties, ST_AsGeoJSON(geom), id FROM gNaN_geodatasets;
    ERROR:  relation "gnan_geodatasets" does not exist
    LINE 1: SELECT properties, ST_AsGeoJSON(geom), id FROM gNaN_geodatas...

This is exactly the same error that gets triggered when I use the `curl` command.   
I get the name of my file querying this other table though:

    db=# SELECT * FROM geodatasets;
     id |     name      | filename | num_features | start_time_field | end_time_field |      table       |         createdAt         |          updatedAt   ----+---------------+----------+--------------+------------------+----------------+------------------+---------------------------+----------------------------
      1 | aviris_ng_001 |          |            2 |                  |                | gNaN_geodatasets | 2024-10-29 10:04:42.04+00 | 2024-10-29 14:51:32.669+00
    (1 row)

Any idea why my geojson file is assigned to the `gNAN_geodatasets` table?
I tried to pull in your latest fix but I get the same error..

This is the content of my geojson file if it can help:

    {
	"type": "FeatureCollection",
	"features": [{
		"id": "0",
		"type": "Feature",
		"properties": {
			"name": "ang20210630t132013_rfl",
			"quicklook": "ang20210630t132013_rfl_rgb_norm.tif"
		},
		"geometry": {
			"type": "Polygon",
			"coordinates": [
				[
					[-4.14429, 39.958304],
					[-4.147791, 40.167243],
					[-4.186655, 40.166851],
					[-4.183035, 39.957915],
					[-4.14429, 39.958304]
				]
			]
		}
	}, {
		"id": "1",
		"type": "Feature",
		"properties": {
			"name": "ang20210630t132835_rfl",
			"quicklook": "ang20210630t132835_rfl_rgb_norm.tif"
		},
		"geometry": {
			"type": "Polygon",
			"coordinates": [
				[
					[-4.107523, 39.959435],
					[-4.110901, 40.167746],
					[-4.149766, 40.167366],
					[-4.146269, 39.959059],
					[-4.107523, 39.959435]
				]
			]
		}
	}]
    }

**Comment by sparkvilla** [comment]
I figured that Postgres psql needs escaping for capital letters.

This means that I can execute your query like this:

    SELECT properties, ST_AsGeoJSON(geom), id FROM "gNaN_geodatasets";

note that `gNaN_geodatasets` is quoted now. This return:

         properties | st_asgeojson | id 
         ------------+--------------+----
         (0 rows)

**Comment by tariqksoliman** [comment]
Awesome and good catch!

The fix I put in https://github.com/NASA-AMMOS/MMGIS/commit/066447aeabeae8fadca5708939acbd86eaa0cdf8 would only be for geodatasets created going forward.

It looks like, somewhere down the road, that an, unnecessary parseInt or sequelize or postgres upgrade might have caused the NaN to enter in -- which includes capital letters and breaks the query.

I bet if you make a new geodataset, that one will work.

Again, thank you for finding this.

**Comment by sparkvilla** [comment]
You are welcome! I renamed the geojson file and now when I use the curl command I get the data back:

    {"type":"FeatureCollection","features":[{"type":"Feature","properties":

    {"name":"ang20210630t132013_rfl","quicklook":"ang20210630t132013_rfl_rgb_norm.tif","_":{"idx":1}},"geometry":   

    {"type":"Polygon","coordinates":[[[-4.14429,39.958304],[-4.147791,40.167243],[-4.186655,40.166851],

    [-4.183035,39.957915],[-4.14429,39.958304]]]}},{"type":"Feature","properties":

     {"name":"ang20210630t132835_rfl","quicklook":"ang20210630t132835_rfl_rgb_norm.tif","_":{"idx":2}},"geometry":

     {"type":"Polygon","coordinates":[[[-4.107523,39.959435],[-4.110901,40.167746],[-4.149766,40.167366],

     [-4.146269,39.959059],[-4.107523,39.959435]]]}}]}

and the polygons are showing on the map. Thanks for your support!
