### ISSUE TITLE
docker-compose ECONNREFUSED 

### ISSUE THREAD

**Issue by kidpixo** [NASA-AMMOS/MMGIS#74]
I'm trying to use docker-compose and `npm` keep complaining about 

```
{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":5432}
``` 
I suspect this this is linked to .env `DB_HOST=localhost` , I changed to `DB_HOST=db` to reflect database container name from `docker-compose.yml` and it seems to work.

**Comment by tariqksoliman** [comment]
Thanks! Added a small comment to `sample.env` too to possibly help anyone in the future.
