### ISSUE TITLE
Installing with Docker

### ISSUE THREAD

**Issue by ChandlerKilpatrick1** [NASA-AMMOS/MMGIS#8]
Hey all, 

I'm trying to install MMGIS with the Docker but am unsure what the `<image tag>` should be. 

Any suggestions?

Best, 
Chandler Kilpatrick

**Comment by Costigan** [comment]
Chandler, this is Mark Shirley. I think I can answer this question about MMGIS and docker for you.  Give me a call when you get a chance.

**Comment by fcalef** [comment]
Sounds good. If you have followup questions, please let us know.

**Comment by ChandlerKilpatrick1** [comment]
I'm trying to evaluate MMGIS for one of the teams that I'm on and have had trouble getting it to run on Mac. Do you plan to create officially supported installation instructions for macOS and Windows?

**Comment by fcalef** [comment]
We've run MMGIS on Windows and it should run on macOS. Can you be more specific about your issue?

**Comment by ChandlerKilpatrick1** [comment]
I have been having trouble with the Postgres server setup. Is there a way that you can provide more documentation on that side (specifically starting with steps two and three on the system requirements section).

**Comment by fcalef** [comment]
I did verify that I could get it working on my macOS (Mojave 10.14.6). The installation description is lacking in the Postgres setup part. Here's what I did:
1) Download the latest version of Postgres. I grabbed version 12.4 for MacOS here: https://www.enterprisedb.com/downloads/postgres-postgresql-downloads
Make sure to record the username and password you enter in.
2) After installing Postgres, use the 'Application Stack Builder' (which comes with the above download) to install PostGIS.
3) Use the install 'SQL Shell' to log into Postgres. Then, it will prompt you for the username and password above. Afterwards, use the following commands:
CREATE DATABASE mmgis;
\c mmgis
CREATE EXTENSION  postgis;
exit
----------
The above will create a database for the MMGIS instance and enable the spatial functionality.
4) Proceed to alter the .env file with the database name (mmgis), username (postgres), and password (whatever you entered).
5) Then you should be able to do the `npm start` command in the root of the MMGIS install and continue on.
Try that and if you have more questions, please ask!

**Comment by ChandlerKilpatrick1** [comment]
While trying to install PostGIS in the Application Stack Builder, I get the following error.
[
<img width="619" alt="Screen Shot 2020-09-30 at 12 29 12 PM" src="https://user-images.githubusercontent.com/46333626/94731011-f6d22e00-0318-11eb-94b7-943c064ff805.png">
](url)

I then run the code given(which has the be manually retyped because they don't let you copy from the GUI) it says "command not found". 
Is this a common error/mistake?

**Comment by fcalef** [comment]
This is not a common error. The error message makes me think you don't have sudo privileges or the proper access level to install POSTGIS. I do know that I had issues with the Stack Builder if I selected too many things to install. Perhaps try just installing POSTGIS only when using it?

The other, slightly extreme, option is to try a different Postgres/POSTGIS install. Uninstall your exist Postgres and try this one: https://postgresapp.com/
